WEB_APP_DIR = '../web/build'
POLAR_NAME = 'polar.txt'
GPX_ARCHIVE_NAME = 'nav.gpx'
GPX_CUR_ROUTE_NAME = 'current_route.gpx'
UPDATE_PKG_NAME = 'otto-pi-update.tgz'
PHRF_TABLE = 'phrf.csv'
BT_CONF_NAME = 'bt_conf.json'
