openapi: 3.0.0

servers:
  - description: localhost
    url: http://localhost:5555/ottopi

info:
  description: APIs to interact with Otto Pi
  version: "1.0.0"
  title: Otto Pi API
  contact:
    email: spodshivalov@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: navigation
    description: Navigation control APIs

paths:
########################################################################################################################
#  /navigation
########################################################################################################################
  /wpts:
    get:
      operationId: nav.get_wpts
      tags:
        - navigation
      summary: Get list of WPTs
      description: Get list of WPTs
      responses:
        '200':
          description: List of waypoints
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WayPoints'


########################################################################################################################
# Components
########################################################################################################################
components:
  schemas:

    WayPoints:
      type: object
      required:
        - wpts
      properties:
        wpts:
          description: List of waypoints
          type: array
          items:
            $ref: '#/components/schemas/Waypoint'

    Waypoint:
      description: Waypoint
      type: object
      required:
        - name
        - latitude
        - longitude
      properties:
        name:
          description: Waypoint name
          type: string
        latitude:
          description: Degrees of latitude
          minimum: -90
          maximum: 90
          type: number
        longitude:
          description: Degrees of longitude
          minimum: -180
          maximum: 180
          type: number
