openapi: 3.0.0

servers:
  - description: localhost
    url: http://localhost:5555

info:
  description: APIs to interact with Otto Pi
  version: "1.0.0"
  title: Otto Pi API
  contact:
    email: spodshivalov@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: nav
    description: Navigation data REST APIs
  - name: web
    description: Paths to acess the builtin Web site
  - name: autopilot
    description: Autopilot control REST APIs

paths:
########################################################################################################################
#  Static web page hosting REACT app
########################################################################################################################
  /ottopi:
    get:
      operationId: rest_api.root_page
      tags:
        - web
      summary: Serves index.html of React app
      description: Serves index.html of React app
      responses:
        '200':
          description: Successfully loaded html page.
          content:
            text/html:   # Add the media type here
              schema:
                type: string

########################################################################################################################
#  Static web page hosting REACT app
########################################################################################################################
  /ottopi/{name}:
    get:
      operationId: rest_api.static_page
      tags:
        - web
      summary: Serves React app
      description: Serves React app
      parameters:
        - in: path
          name: name
          schema:
            type: string
            format: path
          required: false
          description: url path
      responses:
        '200':
          description: Successfully loaded html page.
          content:
            text/html:   # Add the media type here
              schema:
                type: string

########################################################################################################################
#  /navigation
########################################################################################################################
  /nav:
    get:
      operationId: rest_api.get_raw_instr
      tags:
        - nav
      summary: Get raw instrument data
      description: Get raw instrument data
      responses:
        '200':
          description: Raw instrument data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RawInstrData'

  /wpts:
    get:
      operationId: rest_api.get_wpts
      tags:
        - nav
      summary: Get list of waypoints
      description: Get list of waypoints
      responses:
        '200':
          description: List of waypoints
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WayPoints'

  /logs:
    get:
      operationId: rest_api.get_logs
      tags:
        - nav
      summary: Get list of log files
      description: Get list of log files
      responses:
        '200':
          description: List of log files
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /log/{name}:
    get:
      operationId: rest_api.get_log
      tags:
        - nav
      summary: Download log file
      description: Download log files
      parameters:
        - in: path
          name: name
          schema:
            type: string
            format: path
          required: true
          description: log name
      responses:
        '200':
          description: Log file
          content:
            octet/binary:
              schema:
                type: string
                format: binary

  /all_logs.zip:
    get:
      operationId: rest_api.zip_all_logs
      tags:
        - nav
      summary: Download all log files in one zip
      description: Download all log files in one zip
      responses:
        '200':
          description: ZIP file
          content:
            octet/binary:
              schema:
                type: string
                format: binary

  /goto_wpt:
    post:
      operationId: rest_api.goto_wpt
      tags:
        - nav
      summary: Set destination WPT
      description: Set destination WPT
      requestBody:
        description: Destination WPT
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Waypoint'
      responses:
        '200':
          description: Successfully set
          content:
            text/html:
              schema:
                type: string

  /polars:
    post:
      operationId: rest_api.polars_upload
      tags:
        - nav
      summary: Uplaod file containing polras data
      description: Uplaod file containing polras data
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfull upload
          content:
            text/html:   # Add the media type here
              schema:
                type: string


  /gpx:
    post:
      operationId: rest_api.gpx_upload
      tags:
        - nav
      summary: Uplaod GPX file containing routes and waypoints
      description:  Uplaod GPX file containing routes and waypoints
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully loaded html page.
          content:
            text/html:   # Add the media type here
              schema:
                type: string

########################################################################################################################
#  /autopilot
########################################################################################################################
#  /autopilot/engage:
#  /autopilot/steer:
  /autopilot/tack:
    post:
      operationId: rest_api.tack
      tags:
        - autopilot
      summary: Instruct autopilot to tack
      description: Instruct autopilot to tack (or gybe if going downwind)
      responses:
        '200':
          description: Command accepted
          content:
            text/html:
              schema:
                type: string

  /autopilot/steer/{degrees}:
    post:
      operationId: rest_api.steer
      tags:
        - autopilot
      summary: Instruct autopilot to change course
      description: Instruct autopilot to change course by amount degrees specified in parameters
      parameters:
        - in: path
          name: degrees
          schema:
            type: string
          required: true
          description: Amount of degrees to change course (negative left positive right)
      responses:
        '200':
          description: Command accepted
          content:
            text/html:
              schema:
                type: string


########################################################################################################################
# Components
########################################################################################################################
components:
  schemas:

    WayPoints:
      type: object
      required:
        - wpts
      properties:
        wpts:
          description: List of waypoints
          type: array
          items:
            $ref: '#/components/schemas/Waypoint'

    Waypoint:
      description: Waypoint
      type: object
      required:
        - name
        - lat
        - lon
      properties:
        name:
          description: Waypoint name
          type: string
        lat:
          description: Degrees of latitude
          minimum: -90
          maximum: 90
          type: number
        lon:
          description: Degrees of longitude
          minimum: -180
          maximum: 180
          type: number
        active:
          description: We are navigating to this waypoint
          type: boolean

    RawInstrData:
      description: Raw Instruments Data
      type: object
      required:
        - utc
      properties:
        utc:
          description: UTC time stamp
          type: string
        awa:
          description: Apparent Wind Angle (degrees)
          minimum: -180
          maximum: 180
          type: number
        aws:
          description: Apparent Wind Speed (knots)
          minimum: 0
          maximum: 100
          type: number
